export default [
    {
        image2:'assets/images/product-image/electronic/1.jpg',
        image1:'assets/images/product-image/electronic/1.jpg',
        title:'STUDIO DESIGN',
        description:'Juicy Couture Juicy Quilted Ter..',
        oldPrice:'0',
        currentPrice:'Ksh 200',
        discount:'0%',
        rating:'2',
        status:false,
    },
    {
        image2:'assets/images/product-image/electronic/1.jpg',
        image1:'assets/images/product-image/electronic/1.jpg',
        title:'STUDIO DESIGN',
        description:'Juicy Couture Juicy Quilted Ter..',
        oldPrice:'0',
        currentPrice:'Ksh 200',
        discount:'0%',
        rating:'2',
        status:false,
    },
    {
        image2:'assets/images/product-image/electronic/1.jpg',
        image1:'assets/images/product-image/electronic/1.jpg',
        title:'STUDIO DESIGN',
        description:'Juicy Couture Juicy Quilted Ter..',
        oldPrice:'0',
        currentPrice:'Ksh 200',
        discount:'0%',
        rating:'2',
        status:false,
    },
    {
        image2:'assets/images/product-image/electronic/1.jpg',
        image1:'assets/images/product-image/electronic/1.jpg',
        title:'STUDIO DESIGN',
        description:'Juicy Couture Juicy Quilted Ter..',
        oldPrice:'0',
        currentPrice:'Ksh 200',
        discount:'0%',
        rating:'2',
        status:false,
    },
    {
        image2:'assets/images/product-image/electronic/1.jpg',
        image1:'assets/images/product-image/electronic/1.jpg',
        title:'STUDIO DESIGN',
        description:'Juicy Couture Juicy Quilted Ter..',
        oldPrice:'0',
        currentPrice:'Ksh 200',
        discount:'0%',
        rating:'2',
        status:false,
    },
]