export default [
         {
             id:'1',
             Title:'Electronics',

             shops:[
                  {
                   id:'1',
                   title:"ndiema",
                  },
                  {
                    id:'2',
                    title:"ndiema",
                   },
                   {
                    id:'3',
                    title:"ndiema",
                   },
                   {
                    id:'4',
                    title:"ndiema",
                   },
                   {
                    id:'5',
                    title:"ndiema",
                   },
                   {
                    id:'6',
                    title:"ndiema",
                   },
                ]
         },
         {
            id:'2',
            Title:'Electronics',

            shops:[
                 {
                  id:'7',
                  title:"ndiema",
                 },
                 {
                   id:'8',
                   title:"ndiema",
                  },
                  {
                   id:'9',
                   title:"ndiema",
                  },
                  {
                   id:'10',
                   title:"ndiema",
                  },
                  {
                   id:'11',
                   title:"ndiema",
                  },
                  {
                   id:'12',
                   title:"ndiema",
                  },
               ]
        }
]